server:
  port: 8050
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

fact:
  url: ${FACT_API_URL:http://localhost:8080}
  endpoint:
    all-court-data: /search/results.json?q=

spring:
  config:
    import: "optional:configtree:/mnt/secrets/fact/"
  application:
    name: FACT Cron Trigger

azure:
  blob:
    connection-string: ${STORAGE_ACCOUNT_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=factlocal;AccountKey=cmVmb3Jtc2NhbmtleQo=;BlobEndpoint=http://localhost:10000/factlocal;}
