server:
  port: 8050
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

app:
  trigger-type: ${TRIGGER_TYPE}
  enabled: ${TRIGGER_ENABLED:true}

fact:
  url: ${FACT_API_URL:http://localhost:8080}
  endpoint:
    all-court-data: /search/results.json?q=

fact-data-api:
  url: ${FACT_DATA_API_URL:http://localhost:8989}
  endpoint:
    delete-audits: /audits/v1
    delete-users: /user/v1/retention
slack:
  token-daily-checks: ${SLACK_TOKEN}
  channel-id-daily-checks: ${SLACK_CHANNEL_ID}

spring:
  config:
    import: "optional:configtree:/mnt/secrets/*/"
  application:
    name: FACT Cron Trigger
  cloud:
    openfeign:
      oauth2:
        enabled: false
  security:
    oauth2:
      client:
        registration:
          fact-data-api:
            authorization-grant-type: client_credentials
            client-id: ${FACT_CRON_TRIGGER_CLIENT_ID}
            client-secret: ${FACT_CRON_TRIGGER_CLIENT_SECRET}
            provider: azure-ad
            scope: api://${FACT_DATA_API_APP_REGISTRATION_ID}/.default
        provider:
          azure-ad:
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token

azure:
  blob:
    connection-string: ${STORAGE_ACCOUNT_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=factlocal;AccountKey=cmVmb3Jtc2NhbmtleQo=;BlobEndpoint=http://localhost:10000/factlocal;}
