server:
  port: 8050
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

app:
  trigger-type: ${TRIGGER_TYPE}
  enabled: ${TRIGGER_ENABLED:true}

fact:
  url: ${FACT_API_URL:http://localhost:8080}
  endpoint:
    all-court-data: /search/results.json?q=

fact-data-api:
  url: ${FACT_DATA_API_URL:http://localhost:8989}
  endpoint:
    user: /user/v1
    delete-audits: /audits/v1
    delete-users: /user/v1/retention
  admin-user:
    email: ${FACT_DATA_API_ADMIN_USER_EMAIL}
    role: ${FACT_DATA_API_ADMIN_USER_ROLE}
    sso-id: ${FACT_DATA_API_ADMIN_USER_SSO_ID}
slack:
  token-daily-checks: ${SLACK_TOKEN_DAILY_CHECKS}
  channel-id-daily-checks: ${SLACK_CHANNEL_ID_DAILY_CHECKS}

spring:
  config:
    import: "optional:configtree:/mnt/secrets/fact/"
  application:
    name: FACT Cron Trigger

azure:
  ad:
    tenant-id: ${AZURE_TENANT_ID:}
    client-id: ${AZURE_CLIENT_ID:}
    client-secret: ${AZURE_CLIENT_SECRET:}
    scope: api://${AZURE_APP_REGISTRATION_ID:}/.default
  blob:
    connection-string: ${STORAGE_ACCOUNT_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=factlocal;AccountKey=cmVmb3Jtc2NhbmtleQo=;BlobEndpoint=http://localhost:10000/factlocal;}
