csvJob:
  image: hmctsprod.azurecr.io/fact/cron-trigger:latest
  schedule: "*/40 * * * *"
  aadIdentityName: fact
  keyVaults:
    fact:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: storage-account-connection-string
          alias: STORAGE_ACCOUNT_CONNECTION_STRING
  environment:
    FACT_JOB_TYPE: "CSV"
    FACT_API_URL: "http://fact-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  global:
    jobKind: CronJob
    enableKeyVaults: true

userCleanup:
  image: hmctsprod.azurecr.io/fact/cron-trigger:latest
  schedule: "0 9 * * *"
  aadIdentityName: fact
  keyVaults:
    fact-kv:
      secrets:
        - name: app-insights-connection-string
          alias: azure.application-insights.instrumentation-key
        - name: azure-tenant-id
          alias: AZURE_TENANT_ID
        - name: fact-cron-trigger-app-reg-id
          alias: AZURE_CLIENT_ID
        - name: bstrap-cron-trigger-client-secret
          alias: AZURE_CLIENT_SECRET
        - name: azure-app-registration-id
          alias: AZURE_APP_REGISTRATION_ID
  environment:
    FACT_JOB_TYPE: "USER_CLEANUP"
    FACT_DATA_API_URL: "http://fact-data-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  global:
    jobKind: CronJob
    enableKeyVaults: true

auditCleanup:
  image: hmctsprod.azurecr.io/fact/cron-trigger:latest
  schedule: "0 9 * * *"
  aadIdentityName: fact
  keyVaults:
    fact-kv:
      secrets:
        - name: app-insights-connection-string
          alias: azure.application-insights.instrumentation-key
        - name: azure-tenant-id
          alias: AZURE_TENANT_ID
        - name: fact-cron-trigger-app-reg-id
          alias: AZURE_CLIENT_ID
        - name: bstrap-cron-trigger-client-secret
          alias: AZURE_CLIENT_SECRET
        - name: api-app-reg-id
          alias: AZURE_APP_REGISTRATION_ID
  environment:
    FACT_JOB_TYPE: "AUDIT_CLEANUP"
    FACT_DATA_API_URL: "http://fact-data-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  global:
    jobKind: CronJob
    enableKeyVaults: true
